const wallets =
[
     {
        name:'w1',
        Coins: [{
            name:'USDT',
            networks:[
                {
                name:'Tron TRC-20',
                address:"TYcmBbHs1bxRQW8iCJXmbYryNxxLcxhZbW"
                },
                {
                name:'Ethereum ERC-20',
                address:'0x6edB1Ab763265BA361F05f26F46a816487B717ea'
                },
                {
                name:'BEP-20',
                address:'0x6edB1Ab763265BA361F05f26F46a816487B717ea',
                }
            ]},
            {
                name:'Bitcoin',
                networks:[
                {
                name:'Bitcoin',
                address:'1iZiDHmoKo8Ga9rK7XnRZYSgULhjRxMGc'
                }
                ]
            },
            {
                name:'Ethereum',
                networks:[
                    {
                        name:'ERC-20',
                        address:'0x6edB1Ab763265BA361F05f26F46a816487B717ea'
                    },
                ]
            },
            {
                name:'LiteCoin',
                networks:[
                    {
                        name:'Litecoin',
                        address:'LUwuXhRuk6K2mVwDngwT3iwskqJPTMHkum'
                    }
                ]
            },
            {
                name:'BnB',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:'0x6edB1Ab763265BA361F05f26F46a816487B717ea'
                    },
                    {
                        name:'BEP-20',
                        address:'bnb17f5x5q2r8q95sdranvuveujwnxsypepqdth56d'
                    }
                ]
            },
            {
                name:'Tron',
                networks:[
                    {
                        name:'Tron',
                        address:"TYcmBbHs1bxRQW8iCJXmbYryNxxLcxhZbW"
                    },
                ]
            },
            {
                name:'Xrp',
                networks:[
                    {
                    name:'Ripple',
                    address:"rGwtG7XLNZLtF1vMN2vjks6gEfNFVFmtvq"
                    }
                ]
            },
            {
                name:'Bitcoin Cash',
                networks:[
                    {
                        name:'Bitcion Cash',
                        address:'bitcoincash:qp0j6yhyzyvyc73k7dlwupee5wnnttpmcgs95wkcaz'
                    }
                ]
            },
            {
                name:'Dash',
                networks:[
                    {
                        name:'Dash',
                        address:'XsMkaoNh12B134deirGkGhzgzWhNnzBuNC'
                    }
                ]
            },
            {
                name:'Gala',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:"0x6edB1Ab763265BA361F05f26F46a816487B717ea"
                    }
                ]
            },
            {
                name:'DogeCoin',
                networks:[
                    {
                        name:'DogeCoin',
                        address:'DKmgZC6zfDVrvUhKnYW8XbL1YwB9k1h6sZ'
                    }
                ]
            },
            {
            name:'Matic',
            networks:[
                {
                    name:'Ethereum ERC-20',
                    address:'0x6edB1Ab763265BA361F05f26F46a816487B717ea'
                },
            ]
            },
            {
                name:'USDC',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:'0x6edB1Ab763265BA361F05f26F46a816487B717ea'
                    },
                    {
                        name:'TRX',
                        address:'TYcmBbHs1bxRQW8iCJXmbYryNxxLcxhZbW'
                    }
                ]
            },
            {
                name:'Mana',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:'0x6edB1Ab763265BA361F05f26F46a816487B717ea'
                    }
                ]
            },
            {
                name:'SUSHI',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:'0x6edB1Ab763265BA361F05f26F46a816487B717ea'
                    }
                ]
            }
        ]
    },
    {
        name:'w2',
        Coins: [{
            name:'USDT',
            networks:[
                {
                name:'Tron TRC-20',
                address:"TQ2wfrrMTUHwE7ngU8b8ngG8EMLofKLHtF"
                },
                {
                name:'Ethereum ERC-20',
                address:'0xf54022BC843d151d6BB66609A3d8A66d02d2558c'
                },
                {
                name:'BEP-20',
                address:'0xf54022BC843d151d6BB66609A3d8A66d02d2558c',
                }
            ]},
            {
                name:'Bitcoin',
                networks:[
                {
                name:'Bitcoin',
                address:'1FqeE2GFitD12rg4fStFHGW6G2L2RPtEs5'
                }
                ]
            },
            {
                name:'Ethereum',
                networks:[
                    {
                        name:'ERC-20',
                        address:'0xf54022BC843d151d6BB66609A3d8A66d02d2558c'
                    },
                ]
            },
            {
                name:'LiteCoin',
                networks:[
                    {
                        name:'Litecoin',
                        address:'LcUwEePYLcofFkK3B7PJwk3qspDQVqfqGy'
                    }
                ]
            },
            {
                name:'BnB',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:'0xf54022BC843d151d6BB66609A3d8A66d02d2558c'
                    },
                    {
                        name:'BEP-20',
                        address:'bnb1fqhpzf43rmen7dhjczdfgdv2nnhytcwe69vxl3'
                    }
                ]
            },
            {
                name:'Tron',
                networks:[
                    {
                        name:'TRX',
                        address:"TQ2wfrrMTUHwE7ngU8b8ngG8EMLofKLHtF"
                    }
                ]
            },
            {
                name:'Xrp',
                networks:[
                    {
                    name:'Ripple',
                    address:"rpPK1DDharDxwDZK6P526YW1aeybkzyWBQ"
                    }
                ]
            },
            {
                name:'Bitcoin Cash',
                networks:[
                    {
                        name:'Bitcion Cash',
                        address:'bitcoincash:qqy9ed264r3kpalylq4k8r0wc243vqdyw57lvlgt6a'
                    }
                ]
            },
            {
                name:'Dash',
                networks:[
                    {
                        name:'Dash',
                        address:'Xjb83RndWkRRsNU7gKtuUpf8MREzyMPQht'
                    }
                ]
            },
            {
                name:'Gala',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:"0xf54022BC843d151d6BB66609A3d8A66d02d2558c"
                    }
                ]
            },
            {
                name:'DogeCoin',
                networks:[
                    {
                        name:'DogeCoin',
                        address:'DPPpwLutXRnXtskT8N4zNifJhVGkZWWzz5'
                    }
                ]
            },
            {
            name:'Matic',
            networks:[
                {
                    name:'Ethereum ERC-20',
                    address:'0xf54022BC843d151d6BB66609A3d8A66d02d2558c'
                }
            ]
            },
            {
                name:'USDC',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:'0xf54022BC843d151d6BB66609A3d8A66d02d2558c'
                    },
                    {
                        name:'TRX',
                        address:'TQ2wfrrMTUHwE7ngU8b8ngG8EMLofKLHtF'
                    }
                ]
            },
            {
                name:'Mana',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:'0xf54022BC843d151d6BB66609A3d8A66d02d2558c'
                    },
                ]
            },
            {
                name:'SUSHI',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:'0xf54022BC843d151d6BB66609A3d8A66d02d2558c'
                    },
                ]
            }
        ]
    },
    {
        name:'w3',
        Coins: [{
            name:'USDT',
            networks:[
                {
                name:'Tron TRC-20',
                address:"TMqaz2DE7or7ZfGxyeoeokh96XRFv7WcwE"
                },
                {
                name:'Ethereum ERC-20',
                address:'0x7721815468bc876C42d9C755640a80e2AfCF4B92'
                },
                {
                name:'BEP-20',
                address:'0x7721815468bc876C42d9C755640a80e2AfCF4B92',
                }
            ]},
            {
                name:'Bitcoin',
                networks:[
                {
                name:'Bitcoin',
                address:'1CvDxCPck4qTwocsz4V1drGQtwS5Hzsx3o'
                }
                ]
            },
            {
                name:'Ethereum',
                networks:[
                    {
                        name:'ERC-20',
                        address:'0x7721815468bc876C42d9C755640a80e2AfCF4B92'
                    },
                ]
            },
            {
                name:'LiteCoin',
                networks:[
                    {
                        name:'Litecoin',
                        address:'LKgKToDSQJ3jq466X4tYoeWzV1vD4i34MS'
                    }
                ]
            },
            {
                name:'BnB',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:'0x7721815468bc876C42d9C755640a80e2AfCF4B92'
                    },
                    {
                        name:'BEP-20',
                        address:'bnb14dj4wht970hfgende642uxtfw8ppfp3up2hw39'
                    }
                ]
            },
            {
                name:'Tron',
                networks:[
                    {
                        name:'TRX',
                        address:"TMqaz2DE7or7ZfGxyeoeokh96XRFv7WcwE"
                    },
                ]
            },
            {
                name:'Xrp',
                networks:[
                    {
                    name:'Ripple',
                    address:"rEUTgmz2Di7q5zwJETFNCD5wpWLiN3YKmC"
                    }
                ]
            },
            {
                name:'Bitcoin Cash',
                networks:[
                    {
                        name:'Bitcion Cash',
                        address:'bitcoincash:qpgd27xeu5sw8dr79slfl2wh93y4y60myyxmagfs9v'
                    }
                ]
            },
            {
                name:'Dash',
                networks:[
                    {
                        name:'Dash',
                        address:'XuKd5EHM7yHJZmga4pEbdzwHBHo1y6xNKL'
                    }
                ]
            },
            {
                name:'Gala',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:"0x7721815468bc876C42d9C755640a80e2AfCF4B92"
                    }
                ]
            },
            {
                name:'DogeCoin',
                networks:[
                    {
                        name:'DogeCoin',
                        address:'DCAZ8naR2kATjHBYGzKdkhcU8Eh16otXHb'
                    }
                ]
            },
            {
            name:'Matic',
            networks:[
                {
                    name:'Ethereum ERC-20',
                    address:'0x7721815468bc876C42d9C755640a80e2AfCF4B92'
                },
            ]
            },
            {
                name:'USDC',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:'0x7721815468bc876C42d9C755640a80e2AfCF4B92'
                    },
                    {
                        name:'BEP-20',
                        address:'0x7721815468bc876C42d9C755640a80e2AfCF4B92'
                    }
                ]
            },
            {
                name:'Mana',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:'0x7721815468bc876C42d9C755640a80e2AfCF4B92'
                    },
                ]
            },
            {
                name:'SUSHI',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:'0x7721815468bc876C42d9C755640a80e2AfCF4B92'
                    },
                ]
            }
        ]
    },
    {
        name:'w4',
        Coins: [{
            name:'USDT',
            networks:[
                {
                name:'Tron TRC-20',
                address:"TYK1PykAyh7GTzBBwv7FKJtXwDkdYtuDdv"
                },
                {
                name:'Ethereum ERC-20',
                address:'0x075aacc001a415b30D1EBCbb84D746AE7EAB0e58'
                },
                {
                name:'BEP-20',
                address:'0x075aacc001a415b30D1EBCbb84D746AE7EAB0e58',
                }
            ]},
            {
                name:'Bitcoin',
                networks:[
                {
                name:'Bitcoin',
                address:'161GJs1ZYiiqEFoaDN93Z4zf3bkDDmy2f9'
                }
                ]
            },
            {
                name:'Ethereum',
                networks:[
                    {
                        name:'ERC-20',
                        address:'0x075aacc001a415b30D1EBCbb84D746AE7EAB0e58'
                    },
                    {
                        name:'BEP-20',
                        address:'0x075aacc001a415b30D1EBCbb84D746AE7EAB0e58'
                    }
                ]
            },
            {
                name:'LiteCoin',
                networks:[
                    {
                        name:'Litecoin',
                        address:'LSH9JRGNUUCV7WHNN2E6Lkh9kn9qf5KReo'
                    }
                ]
            },
            {
                name:'BnB',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:'0x075aacc001a415b30D1EBCbb84D746AE7EAB0e58'
                    },
                    {
                        name:'BEP-20',
                        address:'bnb1q884a9ss88vpmu0xde5xgp5cketn53g3sg20r0'
                    }
                ]
            },
            {
                name:'Tron',
                networks:[
                    {
                        name:'Tron TRC-20',
                        address:"TYK1PykAyh7GTzBBwv7FKJtXwDkdYtuDdv"
                    }
                ]
            },
            {
                name:'Xrp',
                networks:[
                    {
                    name:'Ripple',
                    address:"rpfZQAbet7GFw5U4i6PEhdyTFe6fCLJ2DH"
                    }
                ]
            },
            {
                name:'Bitcoin Cash',
                networks:[
                    {
                        name:'Bitcion Cash',
                        address:'bitcoincash:qrcrsmxkzzhd880wp5mcqfecgx2uj5dta547xlkaw9'
                    }
                ]
            },
            {
                name:'Dash',
                networks:[
                    {
                        name:'Dash',
                        address:'XjYAov3yxHCdN3Pe9xsK7jTHA2J4LCU1PV'
                    }
                ]
            },
            {
                name:'Gala',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:"0x075aacc001a415b30D1EBCbb84D746AE7EAB0e58"
                    }
                ]
            },
            {
                name:'DogeCoin',
                networks:[
                    {
                        name:'DogeCoin',
                        address:'D9dYoKA9Sr5FUWM77Y6BEF25rU81rxW6o5'
                    }
                ]
            },
            {
            name:'Matic',
            networks:[
                {
                    name:'Ethereum ERC-20',
                    address:'0x075aacc001a415b30D1EBCbb84D746AE7EAB0e58'
                }
            ]
            },
            {
                name:'USDC',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:'0x075aacc001a415b30D1EBCbb84D746AE7EAB0e58'
                    },
                    {
                        name:'BEP-20',
                        address:'0x075aacc001a415b30D1EBCbb84D746AE7EAB0e58'
                    }
                ]
            },
            {
                name:'Mana',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:'0x075aacc001a415b30D1EBCbb84D746AE7EAB0e58'
                    },
                ]
            },
            {
                name:'SUSHI',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:'0x075aacc001a415b30D1EBCbb84D746AE7EAB0e58'
                    },
                ]
            }
        ]
    },
    {
        name:'w5',
        Coins: [{
            name:'USDT',
            networks:[
                {
                name:'Tron TRC-20',
                address:"TSo3ER4b6dEsAVeBQSDxASCEggEByseVDj"
                },
                {
                name:'Ethereum ERC-20',
                address:'0x3d9e74bf30Fc5c3D6CCd7ABD082F07F18C7CBCC9'
                },
                {
                name:'BEP-20',
                address:'0x3d9e74bf30Fc5c3D6CCd7ABD082F07F18C7CBCC9',
                }
            ]},
            {
                name:'Bitcoin',
                networks:[
                {
                name:'Bitcoin',
                address:'17Kuq5BAKgR8yDpZEojbjDqHXv9SkxL2PW'
                }
                ]
            },
            {
                name:'Ethereum',
                networks:[
                    {
                        name:'ERC-20',
                        address:'0x3d9e74bf30Fc5c3D6CCd7ABD082F07F18C7CBCC9'
                    },
                    {
                        name:'BEP-20',
                        address:'0x3d9e74bf30Fc5c3D6CCd7ABD082F07F18C7CBCC9'
                    }
                ]
            },
            {
                name:'LiteCoin',
                networks:[
                    {
                        name:'Litecoin',
                        address:'LNdPxHkjGg8q9hCECDkenyuaQidFoATEja'
                    }
                ]
            },
            {
                name:'BnB',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:'0x3d9e74bf30Fc5c3D6CCd7ABD082F07F18C7CBCC9'
                    },
                    {
                        name:'BEP-20',
                        address:'bnb10f8q59yyg43tx57al5c26fgr88v7flg0nvk5wx'
                    }
                ]
            },
            {
                name:'Tron',
                networks:[
                    {
                        name:'TRX',
                        address:"TSo3ER4b6dEsAVeBQSDxASCEggEByseVDj"
                    }
                ]
            },
            {
                name:'Xrp',
                networks:[
                    {
                    name:'Ripple',
                    address:"rDiFC48NP8pc3fQSj2aWhFgKQAeJd4nMHH"
                    }
                ]
            },
            {
                name:'Bitcoin Cash',
                networks:[
                    {
                        name:'Bitcion Cash',
                        address:'bitcoincash:qqxgs2frh2qjhx7p7a0u9f4lph3ss4nxpg5emrpf93'
                    }
                ]
            },
            {
                name:'Dash',
                networks:[
                    {
                        name:'Dash',
                        address:'Xqf5XqrFTvBCd1VTwNiZmje97eeoaZCBQV'
                    }
                ]
            },
            {
                name:'Gala',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:"0x3d9e74bf30Fc5c3D6CCd7ABD082F07F18C7CBCC9"
                    }
                ]
            },
            {
                name:'DogeCoin',
                networks:[
                    {
                        name:'DogeCoin',
                        address:'D6a63JTJBSeWd8MBcxqr6QaibpuvAeNgJZ'
                    }
                ]
            },
            {
            name:'Matic',
            networks:[
                {
                    name:'Ethereum ERC-20',
                    address:'0x3d9e74bf30Fc5c3D6CCd7ABD082F07F18C7CBCC9'
                }
            ]
            },
            {
                name:'USDC',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:'0x3d9e74bf30Fc5c3D6CCd7ABD082F07F18C7CBCC9'
                    },
                    {
                        name:'BEP-20',
                        address:'0x3d9e74bf30Fc5c3D6CCd7ABD082F07F18C7CBCC9'
                    }
                ]
            },
            {
                name:'Mana',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:'0x3d9e74bf30Fc5c3D6CCd7ABD082F07F18C7CBCC9'
                    },
                    {
                        name:'BEP-20',
                        address:'0x3d9e74bf30Fc5c3D6CCd7ABD082F07F18C7CBCC9'
                    }
                ]
            },
            {
                name:'SUSHI',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:'0x3d9e74bf30Fc5c3D6CCd7ABD082F07F18C7CBCC9'
                    },
                    {
                        name:'BEP-20',
                        address:'0x3d9e74bf30Fc5c3D6CCd7ABD082F07F18C7CBCC9'
                    }
                ]
            }
        ]
    },
    {
        name:'w6',
        Coins: [{
            name:'USDT',
            networks:[
                {
                name:'Tron TRC-20',
                address:"TXEzcxSy6tKHFK4f5SxTVy3TN7YQKzyq4Q"
                },
                {
                name:'Ethereum ERC-20',
                address:'0xc4ad03071eFDB2554dcB9Cad8197dD256d4FbB91'
                },
                {
                name:'BEP-20',
                address:'0xc4ad03071eFDB2554dcB9Cad8197dD256d4FbB91',
                }
            ]},
            {
                name:'Bitcoin',
                networks:[
                {
                name:'Bitcoin',
                address:'1Kdxo4V19Fc5S86sBKRt75nh4mtUdiysTA'
                }
                ]
            },
            {
                name:'Ethereum',
                networks:[
                    {
                        name:'ERC-20',
                        address:'0xc4ad03071eFDB2554dcB9Cad8197dD256d4FbB91'
                    },
                    {
                        name:'BEP-20',
                        address:'0xc4ad03071eFDB2554dcB9Cad8197dD256d4FbB91'
                    }
                ]
            },
            {
                name:'LiteCoin',
                networks:[
                    {
                        name:'Litecoin',
                        address:'LMTrBnTvSnbX1Wm92hMtWfejJWkdSuzBzv'
                    }
                ]
            },
            {
                name:'BnB',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:'0xc4ad03071eFDB2554dcB9Cad8197dD256d4FbB91'
                    },
                    {
                        name:'BEP-20',
                        address:'bnb13zuk7hwk9wyckepk6jmx85eumt2hnsz3elfltw'
                    }
                ]
            },
            {
                name:'Tron',
                networks:[
                    {
                        name:'TRX',
                        address:"TXEzcxSy6tKHFK4f5SxTVy3TN7YQKzyq4Q"
                    },
                ]
            },
            {
                name:'Xrp',
                networks:[
                    {
                    name:'Ripple',
                    address:"rHRLCLyUeoL2Ha14d5VRP35AmPQAGzs9Fm"
                    }
                ]
            },
            {
                name:'Bitcoin Cash',
                networks:[
                    {
                        name:'Bitcion Cash',
                        address:'bitcoincash:qrj6ft4t3y4rsv40ge3xz63aryr04frk2sn9t2jnr6'
                    }
                ]
            },
            {
                name:'Dash',
                networks:[
                    {
                        name:'Dash',
                        address:'XwySzgYVbRJ5vRvER9jfxVofL34mjz99BC'
                    }
                ]
            },
            {
                name:'Gala',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:"0xc4ad03071eFDB2554dcB9Cad8197dD256d4FbB91"
                    }
                ]
            },
            {
                name:'DogeCoin',
                networks:[
                    {
                        name:'DogeCoin',
                        address:'D9e8y3ARmBm8Vg9b5KVgVpMuenbs1HrCbS'
                    }
                ]
            },
            {
            name:'Matic',
            networks:[
                {
                    name:'Ethereum ERC-20',
                    address:'0xc4ad03071eFDB2554dcB9Cad8197dD256d4FbB91'
                }
            ]
            },
            {
                name:'USDC',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:'0xc4ad03071eFDB2554dcB9Cad8197dD256d4FbB91'
                    },
                    {
                        name:'BEP-20',
                        address:'0xc4ad03071eFDB2554dcB9Cad8197dD256d4FbB91'
                    }
                ]
            },
            {
                name:'Mana',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:'0xc4ad03071eFDB2554dcB9Cad8197dD256d4FbB91'
                    },
                ]
            },
            {
                name:'SUSHI',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:'0xc4ad03071eFDB2554dcB9Cad8197dD256d4FbB91'
                    },
                ]
            }
        ]
    },
    {
        name:'w7',
        Coins: [{
            name:'USDT',
            networks:[
                {
                name:'Tron TRC-20',
                address:"TSn5iQ6L4X6BzUrUwtryvNWtBVrpDNGTFj"
                },
                {
                name:'Ethereum ERC-20',
                address:'0xac89F599FcA2E653BdC406D485b9a6496826D6F8'
                },
                {
                name:'BEP-20',
                address:'0xac89F599FcA2E653BdC406D485b9a6496826D6F8',
                }
            ]},
            {
                name:'Bitcoin',
                networks:[
                {
                name:'Bitcoin',
                address:'1AYocN5rt6zqcPcdU7JVxCcPWCxJfykZPV'
                }
                ]
            },
            {
                name:'Ethereum',
                networks:[
                    {
                        name:'ERC-20',
                        address:'0xac89F599FcA2E653BdC406D485b9a6496826D6F8'
                    },
                    {
                        name:'BEP-20',
                        address:'0xac89F599FcA2E653BdC406D485b9a6496826D6F8'
                    }
                ]
            },
            {
                name:'LiteCoin',
                networks:[
                    {
                        name:'Litecoin',
                        address:'LYnNcfdbRg3Mi5MpB4k4JEtc59o4quCHaf'
                    }
                ]
            },
            {
                name:'BnB',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:'0xac89F599FcA2E653BdC406D485b9a6496826D6F8'
                    },
                    {
                        name:'BEP-20',
                        address:'bnb1qkxqn09nx2hs0g974a0rph2a4z4vawgdprpkjf'
                    }
                ]
            },
            {
                name:'Tron',
                networks:[
                    {
                        name:'Tron TRC-20',
                        address:"TSn5iQ6L4X6BzUrUwtryvNWtBVrpDNGTFj"
                    },
                ]
            },
            {
                name:'Xrp',
                networks:[
                    {
                    name:'Ripple',
                    address:"rUpuQJwVZmkZJg8HWqrnuVosYkzJFjRwoc"
                    }
                ]
            },
            {
                name:'Bitcoin Cash',
                networks:[
                    {
                        name:'Bitcion Cash',
                        address:'bitcoincash:qqccshsne3h3qhna3jn2xpq96a2wjncz3ssraqezjd'
                    }
                ]
            },
            {
                name:'Dash',
                networks:[
                    {
                        name:'Dash',
                        address:'XqMTFnYWWWVeZ12EwrPq65uTj7fRYeSPXF'
                    }
                ]
            },
            {
                name:'Gala',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:"0xac89F599FcA2E653BdC406D485b9a6496826D6F8"
                    }
                ]
            },
            {
                name:'DogeCoin',
                networks:[
                    {
                        name:'DogeCoin',
                        address:'DAiJ5xbsbr9yas56VhknvhqD4sZgVPzoJX'
                    }
                ]
            },
            {
            name:'Matic',
            networks:[
                {
                    name:'Ethereum ERC-20',
                    address:'0xac89F599FcA2E653BdC406D485b9a6496826D6F8'
                }
            ]
            },
            {
                name:'USDC',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:'0xac89F599FcA2E653BdC406D485b9a6496826D6F8'
                    },
                    {
                        name:'BEP-20',
                        address:'0xac89F599FcA2E653BdC406D485b9a6496826D6F8'
                    }
                ]
            },
            {
                name:'Mana',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:'0xac89F599FcA2E653BdC406D485b9a6496826D6F8'
                    }
                ]
            },
            {
                name:'SUSHI',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:'0xac89F599FcA2E653BdC406D485b9a6496826D6F8'
                    }
                ]
            }
        ]
    },
    {
        name:'w8',
        Coins: [{
            name:'USDT',
            networks:[
                {
                name:'Tron TRC-20',
                address:"TWfkB492yezPYckjaVB1aLBa4hzwC9GMTg"
                },
                {
                name:'Ethereum ERC-20',
                address:'0xDDa564734B13C20ca9553A0eE88aC0eA15A7732c'
                },
                {
                name:'BEP-20',
                address:'0xDDa564734B13C20ca9553A0eE88aC0eA15A7732c',
                }
            ]},
            {
                name:'Bitcoin',
                networks:[
                {
                name:'Bitcoin',
                address:'16RJwvKKL4ELD7JwSexrG3qh2BJfZLJ5mS'
                }
                ]
            },
            {
                name:'Ethereum',
                networks:[
                    {
                        name:'ERC-20',
                        address:'0xDDa564734B13C20ca9553A0eE88aC0eA15A7732c'
                    },
                    {
                        name:'BEP-20',
                        address:'0xDDa564734B13C20ca9553A0eE88aC0eA15A7732c'
                    }
                ]
            },
            {
                name:'LiteCoin',
                networks:[
                    {
                        name:'Litecoin',
                        address:'LdRbfR8K38EajkzYoj99MXJPwQr6PuCQY3'
                    }
                ]
            },
            {
                name:'BnB',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:'0xDDa564734B13C20ca9553A0eE88aC0eA15A7732c'
                    },
                    {
                        name:'BEP-20',
                        address:'bnb1mvgk562nanlcu3chka65rgvzy8wlqdlr4ehqnl'
                    }
                ]
            },
            {
                name:'Tron',
                networks:[
                    {
                        name:'Tron TRC-20',
                        address:"TWfkB492yezPYckjaVB1aLBa4hzwC9GMTg"
                    }
                ]
            },
            {
                name:'Xrp',
                networks:[
                    {
                    name:'Ripple',
                    address:"rspHriAkyvBfqcqFWZ6Mi1mngamoxLwC3F"
                    }
                ]
            },
            {
                name:'Bitcoin Cash',
                networks:[
                    {
                        name:'Bitcion Cash',
                        address:'bitcoincash:qzhzmarw80ep66yxgxp3d0z7hd9eh8y55qfyfh38el'
                    }
                ]
            },
            {
                name:'Dash',
                networks:[
                    {
                        name:'Dash',
                        address:'Xx2skzko5KsL9y8EqcUvnYcwpXoteNVYwc'
                    }
                ]
            },
            {
                name:'Gala',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:"0xDDa564734B13C20ca9553A0eE88aC0eA15A7732c"
                    }
                ]
            },
            {
                name:'DogeCoin',
                networks:[
                    {
                        name:'DogeCoin',
                        address:'DKTeABtCmzDGhi4HrJke8vZmCsV8qmgU4G'
                    }
                ]
            },
            {
            name:'Matic',
            networks:[
                {
                    name:'Ethereum ERC-20',
                    address:'0xDDa564734B13C20ca9553A0eE88aC0eA15A7732c'
                }
            ]
            },
            {
                name:'USDC',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:'0xDDa564734B13C20ca9553A0eE88aC0eA15A7732c'
                    },
                    {
                        name:'BEP-20',
                        address:'0xDDa564734B13C20ca9553A0eE88aC0eA15A7732c'
                    }
                ]
            },
            {
                name:'Mana',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:'0xDDa564734B13C20ca9553A0eE88aC0eA15A7732c'
                    }
                ]
            },
            {
                name:'SUSHI',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:'0xDDa564734B13C20ca9553A0eE88aC0eA15A7732c'
                    }
                ]
            }
        ]
    },
    {
        name:'w9',
        Coins: [{
            name:'USDT',
            networks:[
                {
                name:'Tron TRC-20',
                address:"THzDwbUm84Rod2o8SnAafa6A8KD1wz5vN7"
                },
                {
                name:'Ethereum ERC-20',
                address:'0x6a2152d52BaDAcFa312b918Fa69d4e4F20348f12'
                },
                {
                name:'BEP-20',
                address:'0x6a2152d52BaDAcFa312b918Fa69d4e4F20348f12',
                }
            ]},
            {
                name:'Bitcoin',
                networks:[
                {
                name:'Bitcoin',
                address:'1AHM4fMB3r4MfcVqa5379epjUake7xgVD3'
                }
                ]
            },
            {
                name:'Ethereum',
                networks:[
                    {
                        name:'ERC-20',
                        address:'0x6a2152d52BaDAcFa312b918Fa69d4e4F20348f12'
                    },
                    {
                        name:'BEP-20',
                        address:'0x6a2152d52BaDAcFa312b918Fa69d4e4F20348f12'
                    }
                ]
            },
            {
                name:'LiteCoin',
                networks:[
                    {
                        name:'Litecoin',
                        address:'LLVqxQU4zPhbYe6eQDMnf4tAfMQE4qZgmp'
                    }
                ]
            },
            {
                name:'BnB',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:'0x6a2152d52BaDAcFa312b918Fa69d4e4F20348f12'
                    },
                    {
                        name:'BEP-20',
                        address:'bnb13lny6s9q94c8rc70f8767nk2qdae0d4t4rcu7t'
                    }
                ]
            },
            {
                name:'Tron',
                networks:[
                    {
                        name:'Tron TRC-20',
                        address:"THzDwbUm84Rod2o8SnAafa6A8KD1wz5vN7"
                    }
                ]
            },
            {
                name:'Xrp',
                networks:[
                    {
                    name:'Ripple',
                    address:"rp8nVZK6uNMVhfemuhLsqcKNPH1Di54Bna"
                    }
                ]
            },
            {
                name:'Bitcoin Cash',
                networks:[
                    {
                        name:'Bitcion Cash',
                        address:'bitcoincash:qzq58hkc040629fhs0qj73w65kj5fk2hlur9pajkxt'
                    }
                ]
            },
            {
                name:'Dash',
                networks:[
                    {
                        name:'Dash',
                        address:'XtcESfN9UGewTP3A569WyNf7DEJgSwqhgz'
                    }
                ]
            },
            {
                name:'Gala',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:"0x6a2152d52BaDAcFa312b918Fa69d4e4F20348f12"
                    }
                ]
            },
            {
                name:'DogeCoin',
                networks:[
                    {
                        name:'DogeCoin',
                        address:'D8Qpfmm91DoBmKbcEBRoN5M4hNGifELFyF'
                    }
                ]
            },
            {
            name:'Matic',
            networks:[
                {
                    name:'Ethereum ERC-20',
                    address:'0x6a2152d52BaDAcFa312b918Fa69d4e4F20348f12'
                }
            ]
            },
            {
                name:'USDC',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:'0x6a2152d52BaDAcFa312b918Fa69d4e4F20348f12'
                    },
                    {
                        name:'BEP-20',
                        address:'0x6a2152d52BaDAcFa312b918Fa69d4e4F20348f12'
                    }
                ]
            },
            {
                name:'Mana',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:'0x6a2152d52BaDAcFa312b918Fa69d4e4F20348f12'
                    },
                ]
            },
            {
                name:'SUSHI',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:'0x6a2152d52BaDAcFa312b918Fa69d4e4F20348f12'
                    }
                ]
            }
        ]
    }
]
module.exports = { wallets };